## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
#two matricies 
a=[[1,2,3],[2,5,8]]
b=[[3,6,4],[1,5,7]]
#the multiplication of two given matrixes
def mul (x,y):
    assert len(x)==len(y) #if 2 len of matrices not equal print assert error 
    return [x_i*y_i for x_i,y_i in zip(x,y)]
def mul2matrix(a,b):
    c=[]
    for i in range(len(a)):
        c.append(mul(a[i],b[i]))
    return c
print(mul2matrix(a,b))

[[3, 12, 12], [2, 25, 56]]


## Write a NumPy program to compute the determinant of a given square array

In [5]:
#numpy library
import numpy as np
#range of array from 0 to 10
arr= np.arange(0,11)
#show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#sqrt array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

## Write a NumPy program to compute the cross product of two given vectors

In [8]:
#two given vectors
a=[[1,2,3],[2,5,8]]
b=[[3,6,4],[1,5,7]]
#cross product of two given vectors
np.cross(a,b)

array([[-10,   5,   0],
       [ -5,  -6,   5]])

## Write a NumPy program to compute the condition number of a given matrix

In [16]:
#the condition number of a given matrix
a=[[1,2],[3,4]]
r=np.cond(a)
r

AttributeError: module 'numpy' has no attribute 'cond'

## Write a NumPy program to compute the inverse of a given matrix

In [15]:
a=([[1,2],[3,4]])
# the inverse of a given matrix
result=np.inv(a)
result

AttributeError: module 'numpy' has no attribute 'inv'